queue:
  image: rabbitmq:3
  restart: always
  hostname: queue
  ports:
    - "5672:5672"

consumer:
  build: ./Consumer
  restart: always
  links:
    - queue
    - database

database:
  restart: always
  image: sameersbn/postgresql:9.4-17
  hostname: database
  environment:
  - DEBUG=false

  - DB_USER=login
  - DB_PASS=pass
  - DB_NAME=db_hello
