version: "3.3"
services:
  rabbit:
    image: rabbitmq:3.7.3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  consumer:
    build: ./consumer
    hostname: consumer
    links:
      - rabbit
  producer:
    build: ./producer
    hostname: producer
    links:
      - rabbit
