# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mark_as_done',
            field=models.BooleanField(default=False),
        ),
    ]
